### PR TITLE
K8s

### PR DESCRIPTION
**Pull request by idontlikej**
Hi, there. Please review my PR about fixing problems in deployments. It was pretty easy to do. If i need to make any changes in task n7 - let me know, please. Also, I can't recall our discussion about 8th task and gitops. Should i do it as well?

### CODE REVIEW

**Comment by grastenis** [comment]
@idontlikej I can see you did quite well, why not try out to fully complete task 7 and 8? Little hint, they are as easy as others ;)

**Comment by grastenis** [comment]
for task 7, after fixing issue, idea is to expose it via https, would require cert generation
for task 8, you can do it if you feel like it ;)

**Comment by idontlikej** [comment]
> @idontlikej I can see you did quite well, why not try out to fully complete task 7 and 8? Little hint, they are as easy as others ;)
I'll definitely will do them, but i'm quite busy today at work, sorry)

**Comment by idontlikej** [comment]
> @idontlikej I can see you did quite well, why not try out to fully complete task 7 and 8? Little hint, they are as easy as others ;)

@grastenis  I've finished all tasks. Could you please check?

**Comment by idontlikej** [comment]
Hi there. @grastenis, I hope you're doing well) Have you checked the task? Should i do anything else?

**Comment by grastenis** [comment]
Hi @idontlikej, yes, I have run over your solution and passed my comments to Andrew, so no need to do anything, and Ill double check with Andrew where the process is now

**Pull request closed without merging**
